value = float(input())

count100Bills = int(value / 100)
remainingValue = round(value - count100Bills * 100,2 )
count50Bills =  int(remainingValue / 50)
remainingValue = round(remainingValue - count50Bills * 50,2)
count20Bills =  int(remainingValue / 20)
remainingValue = round(remainingValue - count20Bills * 20,2)
count10Bills =  int(remainingValue / 10)
remainingValue = round(remainingValue - count10Bills * 10,2)
count5Bills =  int(remainingValue / 5)
remainingValue = round(remainingValue - count5Bills * 5,2)
count2Bills =  int(remainingValue / 2)
remainingValue = round(remainingValue - count2Bills * 2,2)

print('NOTAS:')
print(f'{count100Bills} nota(s) de R$ 100.00')
print(f'{count50Bills} nota(s) de R$ 50.00')
print(f'{count20Bills} nota(s) de R$ 20.00')
print(f'{count10Bills} nota(s) de R$ 10.00')
print(f'{count5Bills} nota(s) de R$ 5.00')
print(f'{count2Bills} nota(s) de R$ 2.00')

count1Coins = int(remainingValue / 1)
remainingValue = round(remainingValue - count1Coins,2)
count50Coins = int(remainingValue / 0.5)
remainingValue = round(remainingValue - count50Coins * 0.5,2)
count25Coins = int(remainingValue / 0.25)
remainingValue = round(remainingValue - count25Coins * 0.25,2)
count10Coins = int(remainingValue / 0.10)
remainingValue = round(remainingValue - count10Coins * 0.10,2)
count05Coins = int(remainingValue / 0.05)
remainingValue = round(remainingValue - count05Coins * 0.05,2)
count01Coins = int(remainingValue / 0.01)
remainingValue = round(remainingValue - count01Coins * 0.01,2)

print('MOEDAS:')
print(f'{count1Coins} moeda(s) de R$ 1.00')
print(f'{count50Coins} moeda(s) de R$ 0.50')
print(f'{count25Coins} moeda(s) de R$ 0.25')
print(f'{count10Coins} moeda(s) de R$ 0.10')
print(f'{count05Coins} moeda(s) de R$ 0.05')
print(f'{count01Coins} moeda(s) de R$ 0.01')